// hel_svelte/src/lib/UpDw.svelte
<script>
    let mine=""
    let com =Math.floor(Math.random()*100+1);
    let res = ""

    const myclick = () =>{
        console.log(com);
        if(parseInt(mine) == com){
            res+=`${mine} 정답<br>`;
        }else if(parseInt(mine) < com){
            res+=`${mine} 작다<br>`;
        }else{
            res+=`${mine} 크다<br>`;
        }
         mine ="";
    }

</script>


<table>
    <tbody>
    <tr>
        <td>맞출수</td>
        <td>
            <input type="text" id="it" bind:value={mine}/>
        </td>
    </tr>
    <tr>
        <td colSpan="2">
            <input type="button" value="맞춰보기" onclick={myclick}/>
        </td>
    </tr>
    <tr>
        <td colSpan="2">
            <div id="mydiv">{@html res}</div>
        </td>
    </tr>
    </tbody>
</table>

<style>
    table,tr,td{
        border: 1px solid gray;
    }
    input[type='text']{
        width: 40px;
    }
    #mydiv{
        height: 160px;
    }
</style>

// hel_vue/src/components/UpDw.vue
<script setup>
import {onMounted, ref} from 'vue'

const mine = ref("");
const com = ref("");
const res = ref("");


const myclick = () => {
    if(parseInt(mine.value) == com.value){
        res.value+=`${mine.value} 정답<br>`;
        setTimeout(()=>{
          alert("정답")
        },1000)
    }else if(parseInt(mine.value) < com.value){
        res.value+=`${mine.value} 작다<br>`;
    }else{
        res.value+=`${mine.value} 크다<br>`;
    }
     mine.value ="";
}
onMounted(()=>{
  com.value=parseInt(Math.floor(Math.random()*99+1));

  console.log(com.value);
})

</script>

<template>

<table>
    <tbody>
    <tr>
        <td>맞출수</td>
        <td>
            <input type="text" id="it" v-model="mine"/>
        </td>
    </tr>
    <tr>
        <td colSpan="2">
            <input type="button" value="맞춰보기" @click="myclick"/>
        </td>
    </tr>
    <tr>
        <td colSpan="2">
            <div id="mydiv" v-html="res"></div>
        </td>
    </tr>
    </tbody>
</table>

</template>

<style scoped>
  table,tr,td{
      border: 1px solid gray;
  }
  input[type='text']{
      width: 40px;
  }
  #mydiv{
      height: 160px;
  }
</style>
