// hel_react/src/App.jsx

import {useRef, useState} from "react";
import MyInput from "./MyInput.jsx";

function App() {
    let obj = useRef(null);
    let [myobj,setMyobj] = useState("hello");

    const myclick = () =>{
        obj.current.value = "Bye";
        setMyobj("Bye");
    }


  return (
    <>
        <input type="text" ref={obj} defaultValue="hello" readOnly/><br/>
        <MyInput value={myobj} readOnly/><br/>
        <button onClick={myclick}>Change Text</button>
    </>
  )
}

export default App;

// hel_vue/src/App.vue
<script setup>


import {ref} from "vue";
import MyInput from "./components/MyInput.vue";
let obj = ref(null);
let obj_value = ref("hello")

const myclick = () =>{
  obj.value.value = "bye";
  obj_value.value = "bye";
}
</script>

<template>
  <input type="text" value="hello" ref="obj"><br>
  <MyInput :value="obj_value"/><br>
  <button @click="myclick">Change Text</button>
</template>

<style scoped>

</style>
