// hel_vue/src/App.vue
<script setup>


import {ref} from "vue";
import MyInput from "./components/MyInput.vue";
let obj = ref(null);
let obj_value = ref("hello")

const myclick = () =>{
  obj.value.value = "bye";
  obj_value.value = "bye";
}
</script>

<template>
  <input type="text" value="hello" ref="obj"><br>
  <MyInput :value="obj_value"/><br>
  <button @click="myclick">Change Text</button>
</template>

<style scoped>

</style>

// hel_svelte/src/App.svelte
<script>
import MyInside from "./lib/MyInside.svelte";
import MyInput from "./lib/MyInput.svelte";

let obj = null;
let obj_mine = "hello";
const myclick = () =>{
    obj.value = "Good Bye";
    obj_mine = "Good Bye";
}

</script>

<main>


    <input type="text" value="hello" bind:this={obj}/>
    <MyInput bind:value={obj_mine}/>
    <button onclick={myclick}>Change Text</button>
</main>

<style>

</style>
