// hel_vue/src/AppLife.vue
<script setup>


import Life01 from "./components/Life01.vue";
import Life02 from "./components/Life02.vue";
import {ref} from "vue";

const flag_life = ref(true);

const myclick = () =>{
    flag_life.value=!flag_life.value;
}

</script>

<template>
  <template v-if="flag_life">
        <Life01/><br>
  </template>
<template v-else>
  <Life02/><br>
</template>

  <button @click="myclick">toggle</button>
</template>

<style scoped>

</style>

// hel_svelte/src/AppLife.svelte
<script>


import Life01 from "./lib/Life01.svelte";
import Life02 from "./lib/Life02.svelte";

let flag_life = true;

const myclick = ()=>{
    flag_life = !flag_life
}
</script>

<main>
    {#if flag_life}
        <Life01/>
        <br>
    {:else}
        <Life02/>
        <br>
    {/if}


    <button onclick={myclick}>toggle</button>

</main>

<style>

</style>
