// hel_vue/src/AppLife.vue
<script setup>


import Life01 from "./components/Life01.vue";
import Life02 from "./components/Life02.vue";
import {ref} from "vue";

const flag_life = ref(true);

const myclick = () =>{
    flag_life.value=!flag_life.value;
}

</script>

<template>
  <template v-if="flag_life">
        <Life01/><br>
  </template>
<template v-else>
  <Life02/><br>
</template>

  <button @click="myclick">toggle</button>
</template>

<style scoped>

</style>

// hel_react/src/AppLife.jsx
import Life01 from "./Life01.jsx";
import Life02 from "./Life02.jsx";
import { useState } from "react";

function App() {
  const [flag_life, setFlagLife] = useState(true);

  const myClick = () => {
    setFlagLife(!flag_life);
  };

  let content; // JSX 밖에서 먼저 선언

  if (flag_life) {
    content = <Life01 />;
  } else {
    content = <Life02 />;
  }

  return (
    <>
      {content}<br/>
      <button onClick={myClick}>toggle</button>
    </>
  );
}

export default App;
