// hel_vue/src/components/Increase.vue
<script setup>
import {ref} from 'vue'

const count = ref("100")

const myclick = () => {
  let num = parseInt(count.value);
  num++;
  count.value = num.toString();
}

</script>

<template>
  {{ count }}
  <button type="button" @click="myclick">Increase</button>

</template>

<style scoped>

</style>

// hel_react/src/Increase.jsx
import {useState} from 'react'

import './App.css'

function Increase() {
    const [count, setCount] = useState("100")

    const myclick = () => {
        let number = parseInt(count);
        number++;
        setCount(number);
    }

    return (
        <>
            {count}
            <button onClick={myclick}>
                Inclease
            </button>

        </>
    )
}

export default Increase
